name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - ChrisBradford2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request !
  - type: textarea
    id: feature-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Tell us what you need !
      value: "I'm always frustrated when "
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      render: markdown
  - type: textarea
    id: additionnal
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      render: markdown
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
